/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fr.smile.training.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Faq service. Represents a row in the &quot;FAQ_Faq&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fr.smile.training.model.impl.FaqModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fr.smile.training.model.impl.FaqImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see Faq
 * @see fr.smile.training.model.impl.FaqImpl
 * @see fr.smile.training.model.impl.FaqModelImpl
 * @generated
 */
@ProviderType
public interface FaqModel extends BaseModel<Faq>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a faq model instance should use the {@link Faq} interface instead.
	 */

	/**
	 * Returns the primary key of this faq.
	 *
	 * @return the primary key of this faq
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this faq.
	 *
	 * @param primaryKey the primary key of this faq
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this faq.
	 *
	 * @return the uuid of this faq
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this faq.
	 *
	 * @param uuid the uuid of this faq
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this faq.
	 *
	 * @return the entry ID of this faq
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this faq.
	 *
	 * @param entryId the entry ID of this faq
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this faq.
	 *
	 * @return the group ID of this faq
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this faq.
	 *
	 * @param groupId the group ID of this faq
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this faq.
	 *
	 * @return the company ID of this faq
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this faq.
	 *
	 * @param companyId the company ID of this faq
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the question of this faq.
	 *
	 * @return the question of this faq
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this faq.
	 *
	 * @param question the question of this faq
	 */
	public void setQuestion(String question);

	/**
	 * Returns the answer of this faq.
	 *
	 * @return the answer of this faq
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this faq.
	 *
	 * @param answer the answer of this faq
	 */
	public void setAnswer(String answer);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(fr.smile.training.model.Faq faq);

	@Override
	public int hashCode();

	@Override
	public CacheModel<fr.smile.training.model.Faq> toCacheModel();

	@Override
	public fr.smile.training.model.Faq toEscapedModel();

	@Override
	public fr.smile.training.model.Faq toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}